/** Forty high-leverage SMB skills — edit labels to match your curriculum. */
export const smallBusinessSkills: string[] = [
  "Executive dashboard definition",
  "Weekly operating review cadence",
  "Customer intake automation",
  "Invoice and AR aging visibility",
  "Cash runway forecasting",
  "Lead source attribution",
  "CRM hygiene rules",
  "Pipeline stage definitions",
  "SOP authoring with owners",
  "Ticket routing and SLAs",
  "Email triage templates",
  "Meeting memo automation",
  "Calendar blocking for deep work",
  "Hiring scorecard templates",
  "Onboarding checklist automation",
  "Vendor renewal tracking",
  "Contract key date alerts",
  "Inventory reorder signals",
  "Quality control sampling",
  "Customer health scoring",
  "Churn reason taxonomy",
  "NPS / CSAT capture loop",
  "Product usage telemetry basics",
  "Incident postmortem template",
  "Security baseline checklist",
  "Access review cadence",
  "Backup and restore drill",
  "Data classification (PII vs public)",
  "Prompt library for repeated tasks",
  "Document RAG over policies",
  "Internal chatbot over SOPs",
  "Code or script review checklist",
  "CI smoke tests for critical paths",
  "Zapier / iPaaS guardrails",
  "Webhook signature verification",
  "Secrets management hygiene",
  "Cost monitoring for AI usage",
  "Model output logging",
  "Human approval for sensitive actions",
  "Quarterly automation portfolio review",
];
